abstract: Interface with the 'rar' command
author: jean-marc boulade <jmbperl@hotmail.com>
build_requires: 
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Archive-Rar
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Dumper: 0
version: 1.92
